# Describe the additioanl per-field settings this module manages.
field.formatter.third_party.field_formatter_filter:
  type: mapping
  label: 'Field Formatter Filter display settings'
  mapping:
    format:
      type: string
      label: Class
